/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaolj_peripheralservice_I2cDevice */

#ifndef _Included_com_xiaolj_peripheralservice_I2cDevice
#define _Included_com_xiaolj_peripheralservice_I2cDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaolj_peripheralservice_I2cDevice
 * Method:    read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xiaolj_peripheralservice_I2cDevice_read
  (JNIEnv *env, jclass jobj, jint a)
  {
    return a;
  }

#ifdef __cplusplus
}
#endif
#endif
