/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaolj_peripheralservice_UartDevice */

#ifndef _Included_com_xiaolj_peripheralservice_UartDevice
#define _Included_com_xiaolj_peripheralservice_UartDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaolj_peripheralservice_UartDevice
 * Method:    read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xiaolj_peripheralservice_UartDevice_read
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
